import type { Metadata } from "next";
import "../globals.scss";
import Navbar from "@/components/navbar/navbar";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import MobileTopBar from "@/components/mobileTopBar/mobileTopBar";
import MobileNavbar from "@/components/mobileNavbar/mobileNavbar";
import { SessionProvider } from "./sessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session) {
    redirect("/");
  }
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Navbar />
          <MobileTopBar />
          {children}
          <MobileNavbar />
        </SessionProvider>
      </body>
    </html>
  );
}
